// v2/tests/obsidian/frontmatter.test.ts
// Comprehensive tests for frontmatter parsing, section splitting, and round-trip.

import { describe, it, expect } from 'vitest';
import {
  parseNote,
  serializeNote,
  splitSections,
  mergeSections,
  buildFrontmatter,
  parseCbmNodeIds,
  parseTags,
} from '../../src/obsidian/frontmatter.js';

describe('parseNote', () => {
  it('parses a note with frontmatter', () => {
    const content = '---\nkey: value\n---\n\nbody text';
    const result = parseNote(content);
    expect(result.frontmatter.key).toBe('value');
    expect(result.body).toBe('\nbody text');
  });

  it('handles note without frontmatter', () => {
    const content = 'just body text';
    const result = parseNote(content);
    expect(result.frontmatter).toEqual({});
    expect(result.body).toBe('just body text');
  });

  it('handles empty content', () => {
    const result = parseNote('');
    expect(result.frontmatter).toEqual({});
    expect(result.body).toBe('');
  });

  it('handles CRLF line endings', () => {
    const content = '---\r\nkey: value\r\n---\r\nbody';
    const result = parseNote(content);
    expect(result.frontmatter.key).toBe('value');
  });

  it('handles malformed YAML gracefully (does not throw)', () => {
    const content = '---\nkey: [unclosed\n---\nbody';
    // Should not throw — may return null or partial.
    expect(() => parseNote(content)).not.toThrow();
  });

  it('handles frontmatter with array tags', () => {
    const content = '---\ntags:\n  - foo\n  - bar\n---\nbody';
    const result = parseNote(content);
    expect(result.frontmatter.tags).toEqual(['foo', 'bar']);
  });

  it('handles frontmatter with comma-separated tags string', () => {
    const content = '---\ntags: "foo, bar, baz"\n---\nbody';
    const result = parseNote(content);
    expect(parseTags(result.frontmatter)).toEqual(['foo', 'bar', 'baz']);
  });
});

describe('splitSections', () => {
  it('handles note with both sections in correct order', () => {
    const body = '# Title\n\n## AUTO-GENERATED\n\nauto content\n\n---\n\n## HUMAN NOTES\n\nhuman content';
    const result = splitSections(body);
    expect(result.autoGenerated).toContain('auto content');
    expect(result.humanNotes).toContain('human content');
    expect(result.preSectionContent).toContain('# Title');
  });

  it('handles note with only AUTO-GENERATED', () => {
    const body = '# Title\n\n## AUTO-GENERATED\n\nauto content';
    const result = splitSections(body);
    expect(result.autoGenerated).toContain('auto content');
    expect(result.humanNotes).toBe('');
  });

  it('handles note with only HUMAN NOTES', () => {
    const body = '# Title\n\n## HUMAN NOTES\n\nhuman content';
    const result = splitSections(body);
    expect(result.autoGenerated).toBe('');
    expect(result.humanNotes).toContain('human content');
  });

  it('handles note with no sections', () => {
    const body = 'just some content without sections';
    const result = splitSections(body);
    expect(result.autoGenerated).toBe('');
    expect(result.humanNotes).toBe('just some content without sections');
  });

  it('handles reversed section order (HUMAN NOTES before AUTO-GENERATED)', () => {
    const body = '# Title\n\n## HUMAN NOTES\n\nhuman content\n\n## AUTO-GENERATED\n\nauto content';
    const result = splitSections(body);
    // Should NOT mix the sections — HUMAN NOTES is preserved, AUTO-GENERATED treated as missing.
    expect(result.humanNotes).toContain('human content');
    expect(result.autoGenerated).toBe('');
  });

  it('does not split on ## AUTO-GENERATED inside a code block when HUMAN NOTES exists', () => {
    // The HUMAN NOTES section contains a code block with a fake ## AUTO-GENERATED heading.
    // The split must NOT treat the in-code-block heading as the section boundary.
    const body = '# Title\n\n## AUTO-GENERATED\n\nreal auto content\n\n---\n\n## HUMAN NOTES\n\nSome text:\n\n```\n## AUTO-GENERATED\nnot a real section\n```\n\nreal human content';
    const result = splitSections(body);
    // HUMAN NOTES should contain both the code block and the real human content.
    expect(result.humanNotes).toContain('real human content');
    expect(result.humanNotes).toContain('not a real section'); // it's inside the code block, preserved
    // AUTO-GENERATED should be only the real auto content (not the code block content).
    expect(result.autoGenerated).toContain('real auto content');
    expect(result.autoGenerated).not.toContain('not a real section');
  });
});

describe('mergeSections', () => {
  it('roundtrips with splitSections (preserves content)', () => {
    const body = '# Title\n\n## AUTO-GENERATED\n\nauto content\n\n---\n\n## HUMAN NOTES\n\nhuman content';
    const split = splitSections(body);
    const merged = mergeSections(split.preSectionContent, split.autoGenerated, split.humanNotes);
    // Re-split should preserve the human notes content (the critical guarantee).
    const reSplit = splitSections(merged);
    expect(reSplit.humanNotes).toBe(split.humanNotes);
    expect(reSplit.autoGenerated).toContain('auto content');
  });

  it('adds empty HUMAN NOTES placeholder when humanNotes is empty', () => {
    const merged = mergeSections('# Title', 'auto', '');
    expect(merged).toContain('## HUMAN NOTES');
    expect(merged.toLowerCase()).toContain('user');
  });
});

describe('parseCbmNodeIds', () => {
  it('handles number', () => {
    expect(parseCbmNodeIds({ cbm_node_id: 1234 })).toEqual([1234]);
  });

  it('handles array', () => {
    expect(parseCbmNodeIds({ cbm_node_ids: [1, 2, 3] })).toEqual([1, 2, 3]);
  });

  it('handles string', () => {
    expect(parseCbmNodeIds({ cbm_node_id: '1234' })).toEqual([1234]);
  });

  it('handles invalid string', () => {
    expect(parseCbmNodeIds({ cbm_node_id: 'abc' })).toEqual([]);
  });

  it('handles null/undefined', () => {
    expect(parseCbmNodeIds({})).toEqual([]);
    expect(parseCbmNodeIds({ cbm_node_id: null })).toEqual([]);
  });
});

describe('parseTags', () => {
  it('handles array (preserves case)', () => {
    expect(parseTags({ tags: ['Foo', 'BAR'] })).toEqual(['Foo', 'BAR']);
  });

  it('handles comma string (preserves case)', () => {
    expect(parseTags({ tags: 'Foo, Bar, baz' })).toEqual(['Foo', 'Bar', 'baz']);
  });

  it('handles null', () => {
    expect(parseTags({})).toEqual([]);
  });
});

describe('buildFrontmatter', () => {
  it('includes type mapping for each label', () => {
    const labels = ['ArchitectureNote', 'ADR', 'BugNote', 'RefactorPlan', 'LegacyNote', 'Convention', 'Prompt', 'JournalEntry', 'ModuleNote', 'RouteNote', 'RiskNote'];
    for (const label of labels) {
      const fm = buildFrontmatter({
        label,
        status: 'active',
        source: 'human',
        cbm_node_ids: [],
        tags: [],
        updated_at: '2026-07-04T00:00:00Z',
      });
      expect(fm.type).toBeDefined();
      expect(typeof fm.type).toBe('string');
    }
  });
});
