// v2/src/obsidian/frontmatter.ts
// YAML frontmatter parsing and serialization for Obsidian notes.

import * as yaml from 'yaml';

export interface ParsedNote {
  frontmatter: Record<string, unknown>;
  body: string;
}

/**
 * Parse a Markdown note with YAML frontmatter.
 * Frontmatter must be between `---` lines at the very start.
 *
 * R48 (#3): replaced regex-based parsing with line-by-line scanning. The old
 * regex `/^---\r?\n([\s\S]*?)\r?\n?---\r?\n?([\s\S]*)$/` could match `---`
 * inside quoted YAML string values (e.g. `title: "a --- b"`), truncating the
 * frontmatter and corrupting the note on re-export. The line-by-line approach
 * looks for a LINE that is exactly `---`, which correctly handles `---` inside
 * quoted values.
 */
export function parseNote(content: string): ParsedNote {
  // Strip UTF-8 BOM if present (Windows editors sometimes add it).
  const cleanContent = content.replace(/^\uFEFF/, '');
  const lines = cleanContent.split(/\r?\n/);

  // Frontmatter must start with a line that is exactly `---`.
  if (lines.length === 0 || lines[0] !== '---') {
    return { frontmatter: {}, body: cleanContent };
  }

  // Find the closing `---` line (must be a line that is exactly `---`).
  let closeIdx = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i] === '---') {
      closeIdx = i;
      break;
    }
  }

  if (closeIdx === -1) {
    // No closing `---` — treat entire content as body.
    return { frontmatter: {}, body: cleanContent };
  }

  const fmStr = lines.slice(1, closeIdx).join('\n');
  const body = lines.slice(closeIdx + 1).join('\n');

  let fm: Record<string, unknown>;
  try {
    const parsed = yaml.parse(fmStr);
    fm = (parsed && typeof parsed === 'object' && !Array.isArray(parsed))
      ? parsed as Record<string, unknown>
      : {};
  } catch {
    // Malformed YAML — return empty frontmatter, treat remaining content as body.
    return { frontmatter: {}, body };
  }

  return { frontmatter: fm, body };
}

/**
 * Serialize frontmatter + body back to Markdown.
 */
export function serializeNote(frontmatter: Record<string, unknown>, body: string): string {
  const fmYaml = yaml.stringify(frontmatter, { sortMapEntries: false }).trim();
  return `---\n${fmYaml}\n---\n\n${body}`;
}

/**
 * Split body into AUTO-GENERATED and HUMAN NOTES sections.
 * Returns { autoGenerated, humanNotes }.
 *
 * Convention:
 *   ## AUTO-GENERATED
 *   ...auto content...
 *
 *   ---
 *
 *   ## HUMAN NOTES
 *   ...human content...
 */
export interface SplitSections {
  autoGenerated: string;
  humanNotes: string;
  preSectionContent: string;  // content before ## AUTO-GENERATED (e.g. the # title)
}

export function splitSections(body: string): SplitSections {
  // Find ## AUTO-GENERATED and ## HUMAN NOTES markers, but skip matches inside fenced code blocks.
  // We track fenced code blocks (``` or ~~~) and only consider headings outside them.
  const lines = body.split('\n');
  let inFence = false;
  let fenceChar = '';
  let autoIdx = -1;
  let humanIdx = -1;
  let charIdx = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!inFence) {
      // Detect fence start: ``` or ~~~ (3+ of the same char).
      const fenceMatch = line.match(/^(`{3,}|~{3,})/);
      if (fenceMatch) {
        inFence = true;
        fenceChar = fenceMatch[1][0]; // ` or ~
      } else if (line.trim() === '## AUTO-GENERATED' && autoIdx === -1) {
        autoIdx = charIdx;
      } else if (line.trim() === '## HUMAN NOTES' && humanIdx === -1) {
        humanIdx = charIdx;
      }
    } else {
      // Check if this line closes the fence: starts with 3+ of the same fence char.
      const closeMatch = line.match(new RegExp('^' + fenceChar + '{3,}'));
      if (closeMatch) {
        inFence = false;
        fenceChar = '';
      }
    }
    charIdx += line.length + 1; // +1 for the \n we split on
  }

  if (autoIdx === -1 && humanIdx === -1) {
    // No sections — treat everything as human notes (be conservative).
    return {
      autoGenerated: '',
      humanNotes: body,
      preSectionContent: '',
    };
  }

  // Compute preSectionContent = everything before the FIRST section marker.
  const firstMarkerIdx = autoIdx === -1 ? humanIdx : (humanIdx === -1 ? autoIdx : Math.min(autoIdx, humanIdx));
  const preSectionContent = body.substring(0, firstMarkerIdx);

  let autoGenerated = '';
  let humanNotes = '';

  // Handle reversed order: if HUMAN NOTES comes BEFORE AUTO-GENERATED, we treat it as malformed.
  // CRITICAL: only capture text between HUMAN NOTES and AUTO-GENERATED markers — NOT everything
  // to end of body (which would include the AUTO-GENERATED section as "human" content).
  if (autoIdx !== -1 && humanIdx !== -1 && humanIdx < autoIdx) {
    // Reversed order — capture only the HUMAN NOTES section up to the AUTO-GENERATED marker.
    const humanSection = body.substring(humanIdx, autoIdx).replace(/^## HUMAN NOTES\r?\n?/, '').trim();
    return {
      autoGenerated: '',
      humanNotes: humanSection,
      preSectionContent: body.substring(0, humanIdx),
    };
  }

  if (autoIdx !== -1 && humanIdx !== -1) {
    // Both sections present, AUTO-GENERATED first.
    autoGenerated = body.substring(autoIdx, humanIdx).replace(/^## AUTO-GENERATED\r?\n?/, '').trim();
    humanNotes = body.substring(humanIdx).replace(/^## HUMAN NOTES\r?\n?/, '').trim();
  } else if (autoIdx !== -1) {
    // Only AUTO-GENERATED.
    autoGenerated = body.substring(autoIdx).replace(/^## AUTO-GENERATED\r?\n?/, '').trim();
    humanNotes = '';
  } else {
    // Only HUMAN NOTES.
    autoGenerated = '';
    humanNotes = body.substring(humanIdx).replace(/^## HUMAN NOTES\r?\n?/, '').trim();
  }

  return { autoGenerated, humanNotes, preSectionContent };
}

export function mergeSections(
  preSectionContent: string,
  autoGenerated: string,
  humanNotes: string
): string {
  const parts: string[] = [];
  if (preSectionContent.trim()) {
    parts.push(preSectionContent.trim());
    parts.push('');
  }
  parts.push('## AUTO-GENERATED');
  parts.push('');
  if (autoGenerated.trim()) {
    parts.push(autoGenerated.trim());
    parts.push('');
  }
  parts.push('---');
  parts.push('');
  parts.push('## HUMAN NOTES');
  parts.push('');
  if (humanNotes.trim()) {
    parts.push(humanNotes.trim());
  } else {
    parts.push('> ✏️ This section belongs to the user. It will **never** be overwritten by Codebase Memory V2.');
    parts.push('');
  }
  return parts.join('\n');
}

/**
 * Standard frontmatter fields for a human node.
 *
 * NOTE: `last_generated` is intentionally omitted from the frontmatter. Previously,
 * it was set to `node.updated_at.split('T')[0]`, which changed whenever updateNode
 * bumped updated_at — even for no-op updates. This caused the exporter's diff check
 * to detect a "change" and re-write the file on every sync, leading to backup
 * accumulation and sync churn. The `updated_at` field in the DB is the source of
 * truth for "last modified"; the vault file doesn't need a redundant date.
 */
export function buildFrontmatter(node: {
  label: string;
  status: string;
  source: string;
  cbm_node_ids: number[];
  tags: string[];
  obsidian_path?: string | null;
  last_synced_at?: string | null;
  updated_at: string;
  related?: {
    modules?: string[];
    routes?: string[];
    files?: string[];
    symbols?: string[];
    adrs?: string[];
    bugs?: string[];
  };
}): Record<string, unknown> {
  const fm: Record<string, unknown> = {
    type: mapLabelToType(node.label),
    source: node.source,
    status: node.status,
  };
  // last_synced is stripped by the exporter's normalizeForDiff before comparison,
  // so it's safe to include. It helps humans see when the file was last synced.
  if (node.last_synced_at) {
    fm.last_synced = node.last_synced_at;
  }
  // Always include cbm_node_ids and tags (even when empty) so mergeFrontmatter
  // can overwrite stale values from the existing vault file.
  fm.cbm_node_ids = node.cbm_node_ids;
  fm.tags = node.tags;
  if (node.related) {
    if (node.related.modules?.length) fm.related_modules = node.related.modules;
    if (node.related.routes?.length) fm.related_routes = node.related.routes;
    if (node.related.files?.length) fm.related_files = node.related.files;
    if (node.related.symbols?.length) fm.related_symbols = node.related.symbols;
    if (node.related.adrs?.length) fm.related_adrs = node.related.adrs;
    if (node.related.bugs?.length) fm.related_bugs = node.related.bugs;
  }
  return fm;
}

function mapLabelToType(label: string): string {
  switch (label) {
    case 'ArchitectureNote': return 'architecture';
    case 'ADR': return 'adr';
    case 'BugNote': return 'bug';
    case 'RefactorPlan': return 'refactor';
    case 'LegacyNote': return 'legacy';
    case 'Convention': return 'convention';
    case 'Prompt': return 'prompt';
    case 'JournalEntry': return 'journal';
    case 'ModuleNote': return 'module';
    case 'RouteNote': return 'route';
    case 'RiskNote': return 'risk';
    default: return label.toLowerCase();
  }
}

/**
 * Parse a frontmatter cbm_node_id field (could be number or array).
 */
export function parseCbmNodeIds(fm: Record<string, unknown>): number[] {
  const v = fm.cbm_node_id ?? fm.cbm_node_ids;
  if (v == null) return [];
  if (Array.isArray(v)) return v.map((x) => Number(x)).filter((n) => !Number.isNaN(n));
  if (typeof v === 'number') return [v];
  if (typeof v === 'string') {
    const n = Number(v);
    return Number.isNaN(n) ? [] : [n];
  }
  return [];
}

/**
 * Parse tags from frontmatter (could be array or comma string).
 */
export function parseTags(fm: Record<string, unknown>): string[] {
  const v = fm.tags;
  if (v == null) return [];
  if (Array.isArray(v)) return v.map((x) => String(x));
  if (typeof v === 'string') return v.split(',').map((s) => s.trim()).filter(Boolean);
  return [];
}
