// v2/src/obsidian/frontmatter.ts
// YAML frontmatter parsing and serialization for Obsidian notes.

import * as yaml from 'yaml';

export interface ParsedNote {
  frontmatter: Record<string, unknown>;
  body: string;
}

/**
 * Parse a Markdown note with YAML frontmatter.
 * Frontmatter must be between `---` lines at the very start.
 */
export function parseNote(content: string): ParsedNote {
  const fmMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!fmMatch) {
    return { frontmatter: {}, body: content };
  }
  const fm = yaml.parse(fmMatch[1]) as Record<string, unknown>;
  return {
    frontmatter: fm ?? {},
    body: fmMatch[2] || '',
  };
}

/**
 * Serialize frontmatter + body back to Markdown.
 */
export function serializeNote(frontmatter: Record<string, unknown>, body: string): string {
  const fmYaml = yaml.stringify(frontmatter, { sortMapEntries: false }).trim();
  return `---\n${fmYaml}\n---\n\n${body}`;
}

/**
 * Split body into AUTO-GENERATED and HUMAN NOTES sections.
 * Returns { autoGenerated, humanNotes }.
 *
 * Convention:
 *   ## AUTO-GENERATED
 *   ...auto content...
 *
 *   ---
 *
 *   ## HUMAN NOTES
 *   ...human content...
 */
export interface SplitSections {
  autoGenerated: string;
  humanNotes: string;
  preSectionContent: string;  // content before ## AUTO-GENERATED (e.g. the # title)
}

export function splitSections(body: string): SplitSections {
  // Find ## AUTO-GENERATED and ## HUMAN NOTES markers
  const autoIdx = body.indexOf('## AUTO-GENERATED');
  const humanIdx = body.indexOf('## HUMAN NOTES');

  if (autoIdx === -1 && humanIdx === -1) {
    // No sections — treat everything as human notes (be conservative)
    return {
      autoGenerated: '',
      humanNotes: body,
      preSectionContent: '',
    };
  }

  const preSectionContent = autoIdx === -1 ? body : body.substring(0, autoIdx);

  let autoGenerated = '';
  let humanNotes = '';

  if (autoIdx !== -1 && humanIdx !== -1) {
    // Both sections present
    autoGenerated = body.substring(autoIdx, humanIdx).replace(/^## AUTO-GENERATED\r?\n?/, '').trim();
    humanNotes = body.substring(humanIdx).replace(/^## HUMAN NOTES\r?\n?/, '').trim();
  } else if (autoIdx !== -1) {
    // Only AUTO-GENERATED
    autoGenerated = body.substring(autoIdx).replace(/^## AUTO-GENERATED\r?\n?/, '').trim();
    humanNotes = '';
  } else {
    // Only HUMAN NOTES
    autoGenerated = '';
    humanNotes = body.substring(humanIdx).replace(/^## HUMAN NOTES\r?\n?/, '').trim();
  }

  return { autoGenerated, humanNotes, preSectionContent };
}

export function mergeSections(
  preSectionContent: string,
  autoGenerated: string,
  humanNotes: string
): string {
  const parts: string[] = [];
  if (preSectionContent.trim()) {
    parts.push(preSectionContent.trim());
    parts.push('');
  }
  parts.push('## AUTO-GENERATED');
  parts.push('');
  if (autoGenerated.trim()) {
    parts.push(autoGenerated.trim());
    parts.push('');
  }
  parts.push('---');
  parts.push('');
  parts.push('## HUMAN NOTES');
  parts.push('');
  if (humanNotes.trim()) {
    parts.push(humanNotes.trim());
  } else {
    parts.push('> ✏️ Cette section appartient à l\'utilisateur. Elle ne sera **jamais** écrasée par Codebase Memory V2.');
    parts.push('');
  }
  return parts.join('\n');
}

/**
 * Standard frontmatter fields for a human node.
 */
export function buildFrontmatter(node: {
  label: string;
  status: string;
  source: string;
  cbm_node_ids: number[];
  tags: string[];
  obsidian_path?: string | null;
  last_synced_at?: string | null;
  updated_at: string;
  related?: {
    modules?: string[];
    routes?: string[];
    files?: string[];
    symbols?: string[];
    adrs?: string[];
    bugs?: string[];
  };
}): Record<string, unknown> {
  const fm: Record<string, unknown> = {
    type: mapLabelToType(node.label),
    source: node.source,
    status: node.status,
    last_generated: node.updated_at.split('T')[0],
  };
  if (node.last_synced_at) {
    fm.last_synced = node.last_synced_at;
  }
  if (node.cbm_node_ids.length > 0) {
    fm.cbm_node_ids = node.cbm_node_ids;
  }
  if (node.tags.length > 0) {
    fm.tags = node.tags;
  }
  if (node.related) {
    if (node.related.modules?.length) fm.related_modules = node.related.modules;
    if (node.related.routes?.length) fm.related_routes = node.related.routes;
    if (node.related.files?.length) fm.related_files = node.related.files;
    if (node.related.symbols?.length) fm.related_symbols = node.related.symbols;
    if (node.related.adrs?.length) fm.related_adrs = node.related.adrs;
    if (node.related.bugs?.length) fm.related_bugs = node.related.bugs;
  }
  return fm;
}

function mapLabelToType(label: string): string {
  switch (label) {
    case 'ArchitectureNote': return 'architecture';
    case 'ADR': return 'adr';
    case 'BugNote': return 'bug';
    case 'RefactorPlan': return 'refactor';
    case 'LegacyNote': return 'legacy';
    case 'Convention': return 'convention';
    case 'Prompt': return 'prompt';
    case 'JournalEntry': return 'journal';
    case 'ModuleNote': return 'module';
    case 'RouteNote': return 'route';
    case 'RiskNote': return 'risk';
    default: return label.toLowerCase();
  }
}

/**
 * Parse a frontmatter cbm_node_id field (could be number or array).
 */
export function parseCbmNodeIds(fm: Record<string, unknown>): number[] {
  const v = fm.cbm_node_id ?? fm.cbm_node_ids;
  if (v == null) return [];
  if (Array.isArray(v)) return v.map((x) => Number(x)).filter((n) => !Number.isNaN(n));
  if (typeof v === 'number') return [v];
  if (typeof v === 'string') {
    const n = Number(v);
    return Number.isNaN(n) ? [] : [n];
  }
  return [];
}

/**
 * Parse tags from frontmatter (could be array or comma string).
 */
export function parseTags(fm: Record<string, unknown>): string[] {
  const v = fm.tags;
  if (v == null) return [];
  if (Array.isArray(v)) return v.map((x) => String(x));
  if (typeof v === 'string') return v.split(',').map((s) => s.trim()).filter(Boolean);
  return [];
}
