// v2/src/obsidian/generator.ts
// Generate Obsidian vault notes from human memory DB.
// CRITICAL: preserve ## HUMAN NOTES section when regenerating.

import { HumanMemoryStore } from '../human/store.js';
import { HumanNode } from '../human/schema.js';
import { CodeGraphReader } from '../bridge/sqlite-ro.js';
import {
  parseNote,
  splitSections,
  mergeSections,
  buildFrontmatter,
  serializeNote,
} from './frontmatter.js';
import {
  ensureVaultDirs,
  writeNote,
  readNote,
  renderVaultIndex,
  ADR_TEMPLATE,
} from './vault.js';

export interface GenerateOptions {
  project: string;
  vaultPath: string;
  humanStore: HumanMemoryStore;
  codeReader?: CodeGraphReader;
  backupBeforeWrite?: boolean;
  dryRun?: boolean;
  autoGenerateModuleNotes?: boolean;
  autoGenerateRouteNotes?: boolean;
  minDegreeForModuleNote?: number;
}

export interface GenerateResult {
  created: string[];
  updated: string[];
  unchanged: string[];
  backups: string[];
  errors: { path: string; error: string }[];
}

export function generateVault(opts: GenerateOptions): GenerateResult {
  const result: GenerateResult = {
    created: [],
    updated: [],
    unchanged: [],
    backups: [],
    errors: [],
  };

  ensureVaultDirs(opts.vaultPath);

  // 1. Sync all existing human_nodes → vault
  const nodes = opts.humanStore.listNodes(opts.project, { limit: 10000 });
  for (const node of nodes) {
    try {
      const relPath = node.obsidian_path;
      if (!relPath) {
        result.errors.push({ path: `<unknown for node ${node.id}>`, error: 'no obsidian_path' });
        continue;
      }
      const existingContent = readNote(opts.vaultPath, relPath);
      const newContent = renderNoteForVault(node, opts.codeReader);

      if (existingContent === null) {
        // Create new
        if (!opts.dryRun) {
          const writeResult = writeNote(opts.vaultPath, relPath, newContent, {
            backupBeforeWrite: opts.backupBeforeWrite ?? true,
          });
          if (writeResult.backupPath) result.backups.push(writeResult.backupPath);
          if (!opts.dryRun) opts.humanStore.markSynced(node.id, 'export');
        }
        result.created.push(relPath);
      } else {
        // Update — preserve HUMAN NOTES
        const parsed = parseNote(existingContent);
        const sections = splitSections(parsed.body);
        const newAutoGenerated = renderAutoGeneratedSection(node, opts.codeReader);
        const newBody = mergeSections(sections.preSectionContent, newAutoGenerated, sections.humanNotes);
        const newFm = mergeFrontmatter(parsed.frontmatter, buildFrontmatter(node));
        const fullContent = serializeNote(newFm, newBody);

        if (fullContent !== existingContent) {
          if (!opts.dryRun) {
            const writeResult = writeNote(opts.vaultPath, relPath, fullContent, {
              backupBeforeWrite: opts.backupBeforeWrite ?? true,
            });
            if (writeResult.backupPath) result.backups.push(writeResult.backupPath);
            opts.humanStore.markSynced(node.id, 'export');
          }
          result.updated.push(relPath);
        } else {
          result.unchanged.push(relPath);
        }
      }
    } catch (e: any) {
      result.errors.push({ path: node.obsidian_path ?? `<node ${node.id}>`, error: e.message });
    }
  }

  // 2. Auto-generate module notes if requested
  if (opts.autoGenerateModuleNotes && opts.codeReader) {
    const minDegree = opts.minDegreeForModuleNote ?? 20;
    const modules = opts.codeReader.listModules(opts.project, 1000);
    for (const module of modules) {
      const degree = opts.codeReader.getNodeDegree(module.id);
      if (degree < minDegree) continue;

      const slug = module.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const relPath = `Modules/${slug}.md`;
      const existing = readNote(opts.vaultPath, relPath);

      // Only generate if not already present
      if (existing) {
        result.unchanged.push(relPath);
        continue;
      }

      // Check if a human_node already exists for this module
      const existingNode = opts.humanStore.getNodeByObsidianPath(opts.project, relPath);
      if (existingNode) continue;

      const autoContent = renderModuleAutoGenerated(module, degree, opts.codeReader);
      const fm = {
        type: 'module',
        source: 'generated',
        status: 'generated',
        cbm_node_id: module.id,
        cbm_node_type: 'Module',
        last_generated: new Date().toISOString().split('T')[0],
      };
      const body = mergeSections(`# Module: ${module.name}`, autoContent, '');
      const content = serializeNote(fm, body);

      if (!opts.dryRun) {
        // Create human_node record
        opts.humanStore.createNode({
          project: opts.project,
          label: 'ModuleNote',
          title: `Module: ${module.name}`,
          body_markdown: '',
          frontmatter: fm,
          source: 'generated',
          status: 'active',
          cbm_node_ids: [module.id],
          tags: ['module', slug],
          obsidian_path: relPath,
        });
        writeNote(opts.vaultPath, relPath, content, {
          backupBeforeWrite: opts.backupBeforeWrite ?? true,
        });
      }
      result.created.push(relPath);
    }
  }

  // 3. Auto-generate route notes if requested
  if (opts.autoGenerateRouteNotes && opts.codeReader) {
    const routes = opts.codeReader.listRoutes(opts.project, 1000);
    for (const route of routes) {
      const props = JSON.parse(route.properties_json || '{}');
      const method = props.route_method || 'GET';
      const path = props.route_path || route.name;
      const slug = `${method.toLowerCase()}-${path.replace(/[^a-z0-9]+/gi, '-')}`.toLowerCase();
      const relPath = `Routes/${slug}.md`;
      const existing = readNote(opts.vaultPath, relPath);
      if (existing) {
        result.unchanged.push(relPath);
        continue;
      }

      const existingNode = opts.humanStore.getNodeByObsidianPath(opts.project, relPath);
      if (existingNode) continue;

      const autoContent = renderRouteAutoGenerated(route, opts.codeReader);
      const fm = {
        type: 'route',
        source: 'generated',
        status: 'generated',
        cbm_node_id: route.id,
        cbm_node_type: 'Route',
        last_generated: new Date().toISOString().split('T')[0],
      };
      const body = mergeSections(`# Route: ${method} ${path}`, autoContent, '');
      const content = serializeNote(fm, body);

      if (!opts.dryRun) {
        opts.humanStore.createNode({
          project: opts.project,
          label: 'RouteNote',
          title: `Route: ${method} ${path}`,
          body_markdown: '',
          frontmatter: fm,
          source: 'generated',
          status: 'active',
          cbm_node_ids: [route.id],
          tags: ['route', method.toLowerCase()],
          obsidian_path: relPath,
        });
        writeNote(opts.vaultPath, relPath, content, {
          backupBeforeWrite: opts.backupBeforeWrite ?? true,
        });
      }
      result.created.push(relPath);
    }
  }

  // 4. Generate 00_Index.md
  const indexRelPath = '00_Index.md';
  const indexContent = renderVaultIndex({
    projectName: opts.project,
    stats: {
      modulesCount: opts.codeReader?.listModules(opts.project).length ?? 0,
      routesCount: opts.codeReader?.listRoutes(opts.project).length ?? 0,
      adrsCount: opts.humanStore.countNodes(opts.project, 'ADR'),
      bugsCount: opts.humanStore.countNodes(opts.project, 'BugNote'),
      refactorsCount: opts.humanStore.countNodes(opts.project, 'RefactorPlan'),
      notesTotal: opts.humanStore.countNodes(opts.project),
    },
  });
  if (!opts.dryRun) {
    writeNote(opts.vaultPath, indexRelPath, indexContent, {
      backupBeforeWrite: opts.backupBeforeWrite ?? true,
    });
  }

  // 5. Generate ADR template
  const templateRelPath = 'ADR/ADR-000-template.md';
  if (!readNote(opts.vaultPath, templateRelPath) && !opts.dryRun) {
    writeNote(opts.vaultPath, templateRelPath, ADR_TEMPLATE, {
      backupBeforeWrite: false,
    });
  }

  return result;
}

function renderNoteForVault(node: HumanNode, codeReader?: CodeGraphReader): string {
  const fm = buildFrontmatter(node);
  const autoContent = renderAutoGeneratedSection(node, codeReader);
  const body = mergeSections(`# ${node.title}`, autoContent, node.body_markdown);
  return serializeNote(fm, body);
}

function renderAutoGeneratedSection(node: HumanNode, codeReader?: CodeGraphReader): string {
  const lines: string[] = [];

  lines.push('> ⚠️ Cette section est contrôlée par Codebase Memory V2 et peut être régénérée.');
  lines.push('> Ne pas éditer — vos modifications seraient perdues au prochain sync.');
  lines.push('');

  lines.push('### Métadonnées');
  lines.push('');
  lines.push(`- **Type** : ${node.label}`);
  lines.push(`- **Status** : ${node.status}`);
  lines.push(`- **Source** : ${node.source}`);
  lines.push(`- **Slug** : ${node.slug}`);
  lines.push(`- **Créée le** : ${node.created_at.split('T')[0]}`);
  lines.push(`- **Mise à jour le** : ${node.updated_at.split('T')[0]}`);
  if (node.last_synced_at) {
    lines.push(`- **Dernier sync Obsidian** : ${node.last_synced_at}`);
  }
  if (node.author) {
    lines.push(`- **Auteur** : ${node.author}`);
  }
  lines.push('');

  if (node.cbm_node_ids.length > 0) {
    lines.push('### Liens vers le code');
    lines.push('');
    for (const cbmId of node.cbm_node_ids) {
      if (codeReader) {
        const codeNode = codeReader.getNodeById(cbmId);
        if (codeNode) {
          lines.push(`- [[${cbmId}]] — ${codeNode.label}:${codeNode.name} (\`${codeNode.file_path}:${codeNode.start_line}\`)`);
        } else {
          lines.push(`- [[${cbmId}]] — *(code node non trouvé)*`);
        }
      } else {
        lines.push(`- [[${cbmId}]]`);
      }
    }
    lines.push('');
  }

  if (node.tags.length > 0) {
    lines.push('### Tags');
    lines.push('');
    lines.push(node.tags.map((t) => `\`#${t}\``).join(' '));
    lines.push('');
  }

  return lines.join('\n');
}

function renderModuleAutoGenerated(
  module: { id: number; name: string; qualified_name: string; file_path: string; start_line: number; end_line: number; properties_json: string },
  degree: number,
  codeReader: CodeGraphReader
): string {
  const lines: string[] = [];
  const props = JSON.parse(module.properties_json || '{}');

  lines.push('> ⚠️ Cette section est contrôlée par Codebase Memory V2 et peut être régénérée.');
  lines.push('');

  lines.push('### Vue d\'ensemble');
  lines.push('');
  lines.push(`- **Chemin** : \`${module.file_path}\``);
  lines.push(`- **Lignes** : ${module.start_line}-${module.end_line}`);
  lines.push(`- **Degré** : ${degree} ${degree >= 30 ? '⚠️ **critique**' : ''}`);
  lines.push(`- **Qualified name** : \`${module.qualified_name}\``);
  lines.push('');

  const neighbors = codeReader.getNeighbors(module.id, 'both', 50);
  if (neighbors.length > 0) {
    lines.push('### Dépendances (top 50)');
    lines.push('');
    for (const { edge, node } of neighbors.slice(0, 50)) {
      lines.push(`- \`${edge.type}\` ↔ [[${node.id}]] — ${node.label}:${node.name}`);
    }
    lines.push('');
  }

  if (Object.keys(props).length > 0) {
    lines.push('### Propriétés');
    lines.push('');
    for (const [key, value] of Object.entries(props)) {
      lines.push(`- **${key}** : ${JSON.stringify(value)}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function renderRouteAutoGenerated(
  route: { id: number; name: string; qualified_name: string; file_path: string; start_line: number; end_line: number; properties_json: string },
  codeReader: CodeGraphReader
): string {
  const lines: string[] = [];
  const props = JSON.parse(route.properties_json || '{}');

  lines.push('> ⚠️ Cette section est contrôlée par Codebase Memory V2 et peut être régénérée.');
  lines.push('');

  lines.push('### Vue d\'ensemble');
  lines.push('');
  lines.push(`- **Handler** : \`${route.file_path}:${route.start_line}\``);
  lines.push(`- **Qualified name** : \`${route.qualified_name}\``);
  if (props.route_method) lines.push(`- **Méthode HTTP** : ${props.route_method}`);
  if (props.route_path) lines.push(`- **Path** : ${props.route_path}`);
  lines.push('');

  const neighbors = codeReader.getNeighbors(route.id, 'out', 30);
  if (neighbors.length > 0) {
    lines.push('### Flux (handlers, services, repositories)');
    lines.push('');
    for (const { edge, node } of neighbors.slice(0, 30)) {
      lines.push(`- \`${edge.type}\` → [[${node.id}]] — ${node.label}:${node.name}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function mergeFrontmatter(
  existing: Record<string, unknown>,
  fresh: Record<string, unknown>
): Record<string, unknown> {
  // DB wins for technical keys; existing wins for editorial keys
  const editorialKeys = new Set(['title', 'description', 'notes']);
  const result: Record<string, unknown> = { ...existing };
  for (const [k, v] of Object.entries(fresh)) {
    if (!editorialKeys.has(k) || result[k] == null) {
      result[k] = v;
    }
  }
  return result;
}
