// v2/src/obsidian/generator.ts
// Generate Obsidian vault notes from human memory DB.
// CRITICAL: preserve ## HUMAN NOTES section when regenerating.

import { HumanMemoryStore } from '../human/store.js';
import { safeJsonParse, MAX_NODES_PER_LABEL } from '../constants.js';
import { HumanNode } from '../human/schema.js';
import { CodeGraphReader } from '../bridge/sqlite-ro.js';
import {
  parseNote,
  splitSections,
  mergeSections,
  buildFrontmatter,
  serializeNote,
} from './frontmatter.js';
import {
  ensureVaultDirs,
  writeNote,
  readNote,
  renderVaultIndex,
  getAdrTemplate,
} from './vault.js';
import { slugify } from '../human/schema.js';

export interface GenerateOptions {
  project: string;
  vaultPath: string;
  humanStore: HumanMemoryStore;
  codeReader?: CodeGraphReader;
  backupBeforeWrite?: boolean;
  dryRun?: boolean;
  autoGenerateModuleNotes?: boolean;
  autoGenerateRouteNotes?: boolean;
  minDegreeForModuleNote?: number;
}

export interface GenerateResult {
  created: string[];
  updated: string[];
  unchanged: string[];
  backups: string[];
  errors: { path: string; error: string }[];
}

export function generateVault(opts: GenerateOptions): GenerateResult {
  const result: GenerateResult = {
    created: [],
    updated: [],
    unchanged: [],
    backups: [],
    errors: [],
  };

  ensureVaultDirs(opts.vaultPath);

  // 1. Sync all existing human_nodes → vault.
  // Use cursor-based pagination to avoid loading everything into memory.
  const PAGE_SIZE = 500;
  let offset = 0;
  while (true) {
    const page = opts.humanStore.listNodes(opts.project, { limit: PAGE_SIZE, offset });
    if (page.length === 0) break;
    for (const node of page) {
      try {
        const relPath = node.obsidian_path;
        if (!relPath) {
          result.errors.push({
            path: `<unknown for node ${node.id}>`,
            error: `no obsidian_path on node id=${node.id} label=${node.label} title="${node.title}" project="${node.project}"`,
          });
          continue;
        }
        const existingContent = readNote(opts.vaultPath, relPath);
        const newContent = renderNoteForVault(node, opts.codeReader);

        if (existingContent === null) {
          // Create new
          if (!opts.dryRun) {
            const writeResult = writeNote(opts.vaultPath, relPath, newContent, {
              backupBeforeWrite: opts.backupBeforeWrite ?? true,
            });
            if (writeResult.backupPath) result.backups.push(writeResult.backupPath);
            opts.humanStore.markSynced(node.id, 'export');
          }
          result.created.push(relPath);
        } else {
          // Update — preserve HUMAN NOTES
          const parsed = parseNote(existingContent);
          const sections = splitSections(parsed.body);
          const newAutoGenerated = renderAutoGeneratedSection(node, opts.codeReader);
          const newBody = mergeSections(sections.preSectionContent, newAutoGenerated, sections.humanNotes);
          const newFm = mergeFrontmatter(parsed.frontmatter, buildFrontmatter(node));
          const fullContent = serializeNote(newFm, newBody);

          // Compare ignoring last_synced (which changes on every export, causing infinite re-writes).
          // Strip last_synced lines from both contents before comparing.
          const normalizeForDiff = (s: string) => s.replace(/^last_synced:.*$/gm, '');
          if (normalizeForDiff(fullContent) !== normalizeForDiff(existingContent)) {
            if (!opts.dryRun) {
              const writeResult = writeNote(opts.vaultPath, relPath, fullContent, {
                backupBeforeWrite: opts.backupBeforeWrite ?? true,
              });
              if (writeResult.backupPath) result.backups.push(writeResult.backupPath);
              opts.humanStore.markSynced(node.id, 'export');
            }
            result.updated.push(relPath);
          } else {
            result.unchanged.push(relPath);
          }
        }
      } catch (e: any) {
        result.errors.push({ path: node.obsidian_path ?? `<node ${node.id}>`, error: e.message });
      }
    }
    if (page.length < PAGE_SIZE) break;
    offset += PAGE_SIZE;
  }

  // 2. Auto-generate module notes for high-degree modules.
  if (opts.autoGenerateModuleNotes && opts.codeReader) {
    const minDegree = opts.minDegreeForModuleNote ?? 20;
    const modules = opts.codeReader.listModules(opts.project, MAX_NODES_PER_LABEL);
    // Bulk-fetch degrees to avoid N+1.
    const moduleIds = modules.map((m) => m.id);
    const degreeMap = opts.codeReader.getBulkNodeDegrees(moduleIds);
    for (const module of modules) {
      const degree = degreeMap.get(module.id) ?? 0;
      if (degree < minDegree) continue;

      // Use the canonical slugify for consistency with createNode.
      const slug = slugify(module.name);
      if (!slug) continue;
      const relPath = `Modules/${slug}.md`;
      const existing = readNote(opts.vaultPath, relPath);
      if (existing) {
        result.unchanged.push(relPath);
        continue;
      }

      // Check if a human_node already exists for this module.
      const existingNode = opts.humanStore.getNodeByObsidianPath(opts.project, relPath);
      if (existingNode) continue;

      const autoContent = renderModuleAutoGenerated(module, degree, opts.codeReader);
      const fm = {
        type: 'module',
        source: 'generated',
        status: 'active',
        cbm_node_id: module.id,
        cbm_node_type: 'Module',
        last_generated: new Date().toISOString().split('T')[0],
      };
      const body = mergeSections(`# Module: ${module.name}`, autoContent, '');
      const content = serializeNote(fm, body);

      if (!opts.dryRun) {
        try {
          const node = opts.humanStore.createNode({
            project: opts.project,
            label: 'ModuleNote',
            title: `Module: ${module.name}`,
            body_markdown: '',
            frontmatter: fm,
            source: 'generated',
            status: 'active',
            cbm_node_ids: [module.id],
            tags: ['module', slug],
            obsidian_path: relPath,
          });
          const writeResult = writeNote(opts.vaultPath, relPath, content, {
            backupBeforeWrite: opts.backupBeforeWrite ?? true,
          });
          if (writeResult.backupPath) result.backups.push(writeResult.backupPath);
          opts.humanStore.markSynced(node.id, 'export');
        } catch (e: any) {
          result.errors.push({ path: relPath, error: `auto-module-note failed: ${e.message}` });
        }
      }
      result.created.push(relPath);
    }
  }

  // 3. Auto-generate route notes.
  if (opts.autoGenerateRouteNotes && opts.codeReader) {
    const routes = opts.codeReader.listRoutes(opts.project, MAX_NODES_PER_LABEL);
    for (const route of routes) {
      const props = safeJsonParse(route.properties_json, {} as Record<string, any>);
      const method = props.route_method || 'GET';
      const path = props.route_path || route.name;
      // Use slugify for consistency.
      const slug = slugify(`${method}-${path}`);
      if (!slug) continue;
      const relPath = `Routes/${slug}.md`;
      const existing = readNote(opts.vaultPath, relPath);
      if (existing) {
        result.unchanged.push(relPath);
        continue;
      }

      const existingNode = opts.humanStore.getNodeByObsidianPath(opts.project, relPath);
      if (existingNode) continue;

      const autoContent = renderRouteAutoGenerated(route, opts.codeReader);
      const fm = {
        type: 'route',
        source: 'generated',
        status: 'active',
        cbm_node_id: route.id,
        cbm_node_type: 'Route',
        last_generated: new Date().toISOString().split('T')[0],
      };
      const body = mergeSections(`# Route: ${method} ${path}`, autoContent, '');
      const content = serializeNote(fm, body);

      if (!opts.dryRun) {
        try {
          const node = opts.humanStore.createNode({
            project: opts.project,
            label: 'RouteNote',
            title: `Route: ${method} ${path}`,
            body_markdown: '',
            frontmatter: fm,
            source: 'generated',
            status: 'active',
            cbm_node_ids: [route.id],
            tags: ['route', method.toLowerCase()],
            obsidian_path: relPath,
          });
          const writeResult = writeNote(opts.vaultPath, relPath, content, {
            backupBeforeWrite: opts.backupBeforeWrite ?? true,
          });
          if (writeResult.backupPath) result.backups.push(writeResult.backupPath);
          opts.humanStore.markSynced(node.id, 'export');
        } catch (e: any) {
          result.errors.push({ path: relPath, error: `auto-route-note failed: ${e.message}` });
        }
      }
      result.created.push(relPath);
    }
  }

  // 4. Generate 00_Index.md with accurate counts.
  let modulesCount = 0;
  let routesCount = 0;
  if (opts.codeReader) {
    const labelCounts = opts.codeReader.countNodesByLabel(opts.project);
    modulesCount = labelCounts['Module'] ?? 0;
    routesCount = labelCounts['Route'] ?? 0;
  }
  const indexRelPath = '00_Index.md';
  const indexContent = renderVaultIndex({
    projectName: opts.project,
    stats: {
      modulesCount,
      routesCount,
      adrsCount: opts.humanStore.countNodes(opts.project, 'ADR'),
      bugsCount: opts.humanStore.countNodes(opts.project, 'BugNote'),
      refactorsCount: opts.humanStore.countNodes(opts.project, 'RefactorPlan'),
      notesTotal: opts.humanStore.countNodes(opts.project),
    },
  });
  if (!opts.dryRun) {
    writeNote(opts.vaultPath, indexRelPath, indexContent, {
      backupBeforeWrite: opts.backupBeforeWrite ?? true,
    });
  }

  // 5. Generate ADR template (fresh date on each call).
  const templateRelPath = 'ADR/ADR-000-template.md';
  if (!readNote(opts.vaultPath, templateRelPath) && !opts.dryRun) {
    writeNote(opts.vaultPath, templateRelPath, getAdrTemplate(), {
      backupBeforeWrite: false,
    });
  }

  return result;
}

function renderNoteForVault(node: HumanNode, codeReader?: CodeGraphReader): string {
  const fm = buildFrontmatter(node);
  const autoContent = renderAutoGeneratedSection(node, codeReader);
  const body = mergeSections(`# ${node.title}`, autoContent, node.body_markdown);
  return serializeNote(fm, body);
}

function renderAutoGeneratedSection(node: HumanNode, codeReader?: CodeGraphReader): string {
  const lines: string[] = [];

  lines.push('> ⚠️ This section is controlled by Codebase Memory V2 and may be regenerated.');
  lines.push('> Do not edit — your changes would be lost on the next sync.');
  lines.push('');

  lines.push('### Metadata');
  lines.push('');
  lines.push(`- **Type** : ${node.label}`);
  lines.push(`- **Status** : ${node.status}`);
  lines.push(`- **Source** : ${node.source}`);
  lines.push(`- **Slug** : ${node.slug}`);
  lines.push(`- **Created** : ${node.created_at.split('T')[0]}`);
  lines.push(`- **Updated** : ${node.updated_at.split('T')[0]}`);
  if (node.last_synced_at) {
    lines.push(`- **Last sync** : ${node.last_synced_at}`);
  }
  if (node.author) {
    lines.push(`- **Author** : ${node.author}`);
  }
  lines.push('');

  if (node.cbm_node_ids.length > 0) {
    lines.push('### Links to code');
    lines.push('');
    // Bulk-fetch code nodes to avoid N+1.
    if (codeReader) {
      const nodesMap = codeReader.getNodesByIds(node.cbm_node_ids);
      for (const cbmId of node.cbm_node_ids) {
        const codeNode = nodesMap.get(cbmId);
        if (codeNode) {
          lines.push(`- [[${cbmId}]] — ${codeNode.label}:${codeNode.name} (\`${codeNode.file_path}:${codeNode.start_line}\`)`);
        } else {
          lines.push(`- [[${cbmId}]] — *(code node not found)*`);
        }
      }
    } else {
      for (const cbmId of node.cbm_node_ids) {
        lines.push(`- [[${cbmId}]]`);
      }
    }
    lines.push('');
  }

  if (node.tags.length > 0) {
    lines.push('### Tags');
    lines.push('');
    // Render as raw #tag (no backticks) so Obsidian recognizes them as inline tags.
    lines.push(node.tags.map((t) => '#' + t).join(' '));
    lines.push('');
  }

  return lines.join('\n');
}

function renderModuleAutoGenerated(
  module: { id: number; name: string; qualified_name: string; file_path: string; start_line: number; end_line: number; properties_json: string },
  degree: number,
  codeReader: CodeGraphReader
): string {
  const lines: string[] = [];
  const props = safeJsonParse(module.properties_json, {} as Record<string, any>);

  lines.push('> ⚠️ This section is controlled by Codebase Memory V2 and may be regenerated.');
  lines.push('');

  lines.push('### Overview');
  lines.push('');
  lines.push(`- **Path** : \`${module.file_path}\``);
  lines.push(`- **Lines** : ${module.start_line}-${module.end_line}`);
  lines.push(`- **Degree** : ${degree} ${degree >= 30 ? '⚠️ **critical**' : ''}`);
  lines.push(`- **Qualified name** : \`${module.qualified_name}\``);
  lines.push('');

  const neighbors = codeReader.getNeighbors(module.id, 'both', 50);
  if (neighbors.length > 0) {
    lines.push('### Dependencies (top 50)');
    lines.push('');
    for (const { edge, node } of neighbors.slice(0, 50)) {
      lines.push(`- \`${edge.type}\` ↔ [[${node.id}]] — ${node.label}:${node.name}`);
    }
    lines.push('');
  }

  if (Object.keys(props).length > 0) {
    lines.push('### Properties');
    lines.push('');
    for (const [key, value] of Object.entries(props)) {
      lines.push(`- **${key}** : ${JSON.stringify(value)}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function renderRouteAutoGenerated(
  route: { id: number; name: string; qualified_name: string; file_path: string; start_line: number; end_line: number; properties_json: string },
  codeReader: CodeGraphReader
): string {
  const lines: string[] = [];
  const props = safeJsonParse(route.properties_json, {} as Record<string, any>);

  lines.push('> ⚠️ This section is controlled by Codebase Memory V2 and may be regenerated.');
  lines.push('');

  lines.push('### Overview');
  lines.push('');
  lines.push(`- **Handler** : \`${route.file_path}:${route.start_line}\``);
  lines.push(`- **Qualified name** : \`${route.qualified_name}\``);
  if (props.route_method) lines.push(`- **HTTP method** : ${props.route_method}`);
  if (props.route_path) lines.push(`- **Path** : ${props.route_path}`);
  lines.push('');

  const neighbors = codeReader.getNeighbors(route.id, 'out', 30);
  if (neighbors.length > 0) {
    lines.push('### Flow (handlers, services, repositories)');
    lines.push('');
    for (const { edge, node } of neighbors.slice(0, 30)) {
      lines.push(`- \`${edge.type}\` → [[${node.id}]] — ${node.label}:${node.name}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function mergeFrontmatter(
  existing: Record<string, unknown>,
  fresh: Record<string, unknown>
): Record<string, unknown> {
  // DB wins for technical keys; existing wins for editorial keys.
  const editorialKeys = new Set(['title', 'description', 'notes']);
  const result: Record<string, unknown> = { ...existing };
  for (const [k, v] of Object.entries(fresh)) {
    if (!editorialKeys.has(k) || result[k] == null) {
      result[k] = v;
    }
  }
  return result;
}
